version: '{build}'
branches:
  only:
  - feature/nuget
image: Visual Studio 2019
configuration: Release
init:
- cmd: set GITVERSION_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
test: off
artifacts:
- path: artifacts/*nupkg
  name: nuget
deploy:
- provider: Environment
  name: sil-lsdev nuget
notifications:
- provider: GitHubPullRequest
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
